# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CodeCloneTool < Formula
  desc ""
  homepage "https://github.com/Grayson/code-clone-tool"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Grayson/code-clone-tool/releases/download/1.0.0/code-clone-tool_1.0.0_Darwin_arm64.tar.gz"
      sha256 "11ce6f54c4797dedb066eab9ba713e4b762b6fd2e5045010a0a7afd4c19e040a"

      def install
        bin.install "code-clone-tool"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Grayson/code-clone-tool/releases/download/1.0.0/code-clone-tool_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "feb3c87a19cab51bfa9da8249e7d51633e82d82547aec3381c0ceee7d743294e"

      def install
        bin.install "code-clone-tool"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Grayson/code-clone-tool/releases/download/1.0.0/code-clone-tool_1.0.0_Linux_arm64.tar.gz"
      sha256 "0cf794380007d3083332b385f6252ce41eebc332c7c4bf0e66afe58238d33019"

      def install
        bin.install "code-clone-tool"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Grayson/code-clone-tool/releases/download/1.0.0/code-clone-tool_1.0.0_Linux_x86_64.tar.gz"
      sha256 "1bf92caa77563c64d94eaeb76b476f754d68628e3d91292e32337804c64b27a8"

      def install
        bin.install "code-clone-tool"
      end
    end
  end
end
